import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SessionAuthProvider from '@/context/SessionAuthProvider'
import Aside from '@/components/Aside'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='bg-gray-50'>
          <SessionAuthProvider>
            <Aside />
            <div className='sm:ml-64'>
              {children}
            </div>
          </SessionAuthProvider>
        </main>
      </body>
    </html>
  )
}
