import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import Aside from "@/components/Aside";
import { ThemeProvider } from "@/context/TemaProvider";
import { ThemeSwitcher } from "@/components/DarkMode";
import BadgeContextProvider from "@/context/BadgeContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className} bg-slate-50 dark:bg-gray-800`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main>
            <SessionAuthProvider>
              <BadgeContextProvider>
                <Aside />
                <div>
                  <ThemeSwitcher />
                  {children}
                </div>
              </BadgeContextProvider>
            </SessionAuthProvider>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
